import { Message } from "@/types/features/live-chat.types";

// Sample messages matching the reference design - Enhanced for testing
export const sampleMessages: Message[] = [
  {
    id: "1",
    type: "text",
    userId: "1",
    username: "ArtistMaster",
    avatar: "/artist-avatar.png",
    timestamp: new Date(Date.now() - 300000),
    content: "Hey everyone! Just joined the chat 🎨",
    country: "🇺🇸",
    ringColor: "ring-blue-500",
  },
  {
    id: "2",
    type: "text",
    userId: "2",
    username: "KryptoKing",
    avatar: "/krypto-avatar.png",
    timestamp: new Date(Date.now() - 280000),
    content: "Welcome to the casino! @ArtistMaster",
    country: "🇨🇦",
    badge: "legend",
    ringColor: "ring-red-500",
  },
  {
    id: "3",
    type: "text",
    userId: "3",
    username: "DirtyBoga",
    avatar: "/dirty-avatar.png",
    timestamp: new Date(Date.now() - 260000),
    content: "where you from? @ArtistMaster",
    country: "🇬🇧",
    ringColor: "ring-green-500",
    replyCount: 2,
    threadId: "thread-1",
  },
  {
    id: "4",
    type: "text",
    userId: "4",
    username: "MexicanPlayer",
    avatar: "/mex-avatar.png",
    timestamp: new Date(Date.now() - 240000),
    content: "Good luck everyone! 🍀",
    country: "🇲🇽",
    ringColor: "ring-yellow-500",
  },
  {
    id: "5",
    type: "win",
    userId: "5",
    username: "RichKidBF",
    avatar: "/rich-avatar.png",
    timestamp: new Date(Date.now() - 220000),
    game: "Keno",
    amount: 17.505,
    currency: "BFG",
    multiplier: "350.10",
    country: "🇺🇸",
    ringColor: "ring-purple-500",
    replyCount: 3,
    threadId: "thread-2",
  },
  {
    id: "6",
    type: "gif",
    userId: "6",
    username: "GifMaster",
    avatar: "/gif-master-avatar.png",
    timestamp: new Date(Date.now() - 210000),
    gifUrl: "/celebration-gif.png",
    caption: "When you hit the jackpot! @RichKidBF congrats!",
    country: "🇺🇸",
    ringColor: "ring-pink-500",
  },
  {
    id: "7",
    type: "text",
    userId: "7",
    username: "AlphaGamer",
    avatar: "/multi-avatar.png",
    timestamp: new Date(Date.now() - 180000),
    content: "Anyone want to share some tips? @KryptoKing @RichKidBF",
    country: "🇮🇳",
    ringColor: "ring-orange-500",
  },
  {
    id: "8",
    type: "text",
    userId: "8",
    username: "Mussain",
    avatar: "/mussain-avatar.png",
    timestamp: new Date(Date.now() - 160000),
    content:
      "Are you from the Philippines @Joancampos ? Coz we have the same surname haha",
    country: "🇵🇭",
    ringColor: "ring-cyan-500",
    replyCount: 1,
    threadId: "thread-3",
  },
  {
    id: "9",
    type: "text",
    userId: "9",
    username: "User9548070",
    avatar: "/user-avatar.png",
    timestamp: new Date(Date.now() - 140000),
    content: "Testing the chat @ArtistMaster @AlphaGamer",
    country: "🇰🇷",
    ringColor: "ring-green-400",
  },
  {
    id: "10",
    type: "text",
    userId: "10",
    username: "BetMaster",
    avatar: "/reply-avatar.png",
    timestamp: new Date(Date.now() - 120000),
    content: "Let's see some big wins! @RichKidBF show us how it's done",
    country: "🇵🇭",
    ringColor: "ring-blue-400",
  },
  {
    id: "11",
    type: "text",
    userId: "11",
    username: "WinReply",
    avatar: "/win-reply-avatar.png",
    timestamp: new Date(Date.now() - 100000),
    content: "Congrats on that massive win! 🎉 @RichKidBF",
    country: "🇺🇸",
    ringColor: "ring-green-400",
    threadId: "thread-2",
  },
  {
    id: "12",
    type: "text",
    userId: "12",
    username: "GifReply",
    avatar: "/gif-reply-avatar.png",
    timestamp: new Date(Date.now() - 80000),
    content: "That GIF is perfect! 😂 @GifMaster",
    country: "🇨🇦",
    ringColor: "ring-purple-400",
    threadId: "thread-4",
  },
];
